go.mod
go.sum
pkg/vm/engine/tae/common/compare.go
pkg/vm/engine/tae/common/utils.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/index/access/accessif/iface.go
pkg/vm/engine/tae/index/access/impl/ablock.go
pkg/vm/engine/tae/index/basic/filter.go
pkg/vm/engine/tae/index/basic/filter_test.go
pkg/vm/engine/tae/index/basic/tree.go
pkg/vm/engine/tae/index/basic/tree_test.go
pkg/vm/engine/tae/index/basic/zonemap.go
pkg/vm/engine/tae/index/basic/zonemap_test.go
pkg/vm/engine/tae/index/common/errors/errors.go
pkg/vm/engine/tae/index/common/meta.go
pkg/vm/engine/tae/index/common/mock.go
pkg/vm/engine/tae/index/io/zonemap_block.go
pkg/vm/engine/tae/tables/appender.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/segment.go

issue #
Not Available
Not Available
Not Available

add basic pk deduplication

---

pkg/vm/engine/tae/test/tables_test.go
pkg/vm/engine/tae/txn/txnimpl/index.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/txn/txnimpl/txn_test.go

issue #
Not Available
Not Available
Not Available

(tae): fix index related bug

---

pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/iface/handle/block.go
pkg/vm/engine/tae/iface/handle/relation.go
pkg/vm/engine/tae/iface/handle/segment.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/test/txn_test.go
pkg/vm/engine/tae/txn/txnbase/handle.go
pkg/vm/engine/tae/txn/txnbase/store.go
pkg/vm/engine/tae/txn/txnimpl/block.go
pkg/vm/engine/tae/txn/txnimpl/relation.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/updates/blkupdates.go
pkg/vm/engine/tae/updates/chain.go
pkg/vm/engine/tae/updates/colupdates.go

issue #
Not Available
Not Available
Not Available

(tae): add get by filter

---

pkg/vm/engine/tae/logstore/entry/base.go
pkg/vm/engine/tae/logstore/entry/entry_test.go
pkg/vm/engine/tae/logstore/store/file.go
pkg/vm/engine/tae/logstore/store/file_test.go
pkg/vm/engine/tae/logstore/store/history.go
pkg/vm/engine/tae/logstore/store/replayer.go
pkg/vm/engine/tae/logstore/store/store_test.go
pkg/vm/engine/tae/logstore/store/syncbase.go
pkg/vm/engine/tae/logstore/store/types.go
pkg/vm/engine/tae/logstore/store/vfile.go
pkg/vm/engine/tae/logstore/store/vgroup.go
pkg/vm/engine/tae/logstore/store/vinfo.go

issue #
Not Available
Not Available
Not Available

support partial checkpoint

---

pkg/vm/engine/tae/cmd/sample1/main.go
pkg/vm/engine/tae/cmd/sample2/main.go
pkg/vm/engine/tae/cmd/sample3/main.go
pkg/vm/engine/tae/cmd/sample4/main.go
pkg/vm/engine/tae/common/filenames.go
pkg/vm/engine/tae/db/db.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/lock.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/options/cfg.go
pkg/vm/engine/tae/options/options.go
pkg/vm/engine/tae/options/types.go

issue #
Not Available
Not Available
Not Available

(tae): add tae db

---

pkg/vm/engine/tae/catalog/catalog_test.go
pkg/vm/engine/tae/db/db.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/flusher/flusher.go
pkg/vm/engine/tae/flusher/flusher_test.go
pkg/vm/engine/tae/flusher/shard.go
pkg/vm/engine/tae/flusher/types.go
pkg/vm/engine/tae/shard/aware.go
pkg/vm/engine/tae/shard/stats.go
pkg/vm/engine/tae/tables/tables_test.go
pkg/vm/engine/tae/test/tables_test.go
pkg/vm/engine/tae/test/txn_test.go
pkg/vm/engine/tae/testutils/config/options.go
pkg/vm/engine/tae/testutils/helpers.go
pkg/vm/engine/tae/txn/txnimpl/txn_test.go
pkg/vm/engine/tae/updates/chain_test.go

issue #
Not Available
Not Available
Not Available

(tae): add flusher and testutils

---

pkg/vm/engine/tae/catalog/schema.go
pkg/vm/engine/tae/dataio/base.go
pkg/vm/engine/tae/dataio/mock.go
pkg/vm/engine/tae/dataio/types.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/tables/appender.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/node.go
pkg/vm/engine/tae/test/tables_test.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/updates/colchain.go
pkg/vm/engine/tae/updates/colupdate.go
pkg/vm/engine/tae/updates/controller.go
pkg/vm/engine/tae/updates/delete.go

issue #
Not Available
Not Available
Not Available

update for block unload

---

pkg/vm/engine/tae/catalog/schema.go
pkg/vm/engine/tae/flusher/cond.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/node.go
pkg/vm/engine/tae/updates/dataview.go

issue #
Not Available
Not Available
Not Available

(tae): update for block data

---

pkg/vm/engine/tae/dataio/mock.go
pkg/vm/engine/tae/dataio/types.go
pkg/vm/engine/tae/index/access/acif/ifaces.go
pkg/vm/engine/tae/index/basic/zonemap.go
pkg/vm/engine/tae/index/common/meta.go
pkg/vm/engine/tae/index/io/zonemap_block.go
pkg/vm/engine/tae/index/io/zonemap_block_test.go
pkg/vm/engine/tae/tables/appender.go
pkg/vm/engine/tae/tables/block.go

issue #
Not Available
Not Available
Not Available

(tae): update mock index file and some index codes

---

pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/tables/appender.go
pkg/vm/engine/tae/test/tables_test.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/updates/append.go
pkg/vm/engine/tae/updates/controller.go
pkg/vm/engine/tae/updates/controller_test.go

issue #
Not Available
Not Available
Not Available

(tae): update for append node

---

pkg/vm/engine/tae/updates/append.go

issue #
Not Available
Not Available
Not Available

(tae): hot fix

---

pkg/vm/engine/tae/logstore/store/file_test.go
pkg/vm/engine/tae/logstore/store/vfile.go

issue #
Not Available
Not Available
Not Available

fix logstore

---

pkg/vm/engine/tae/catalog/segment.go
pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/iface/data/segment.go
pkg/vm/engine/tae/iface/data/table.go
pkg/vm/engine/tae/tables/appender.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/handle.go
pkg/vm/engine/tae/tables/node.go
pkg/vm/engine/tae/tables/segment.go
pkg/vm/engine/tae/tables/table.go
pkg/vm/engine/tae/test/tables_test.go
pkg/vm/engine/tae/txn/txnimpl/appender.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/updates/controller.go

issue #
Not Available
Not Available
Not Available

rewrite append related code

---

pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/node.go
pkg/vm/engine/tae/test/tables_test.go
pkg/vm/engine/tae/txn/txnimpl/table.go

issue #
Not Available
Not Available
Not Available

(tae): add some test and update to block

---

pkg/vm/engine/tae/container/compute/compute.go
pkg/vm/engine/tae/updates/dataview.go

issue #
Not Available
Not Available
Not Available

add ApplyUpdateToIVector

---

pkg/vm/engine/tae/index/basic/filter.go
pkg/vm/engine/tae/index/io/filter.go
pkg/vm/engine/tae/index/io/filter_test.go

issue #
Not Available
Not Available
Not Available

(tae): add static filter index

---

pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/tables/block.go

issue #
Not Available
Not Available
Not Available

(tae): implement data txn visibilty

---

pkg/vm/engine/tae/container/compute/compute.go
pkg/vm/engine/tae/container/compute/compute_test.go
pkg/vm/engine/tae/container/vector/stdvec.go

issue #
Not Available
Not Available
Not Available

Fix ApplyUpdateToIVector

---

pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/txn/txnimpl/index.go
pkg/vm/engine/tae/txn/txnimpl/table.go

issue #
Not Available
Not Available
Not Available

update for data visibility

---

pkg/vm/engine/tae/index/access/impl/ablock.go
pkg/vm/engine/tae/index/basic/tree_test.go
pkg/vm/engine/tae/index/common/meta.go
pkg/vm/engine/tae/index/io/filter.go
pkg/vm/engine/tae/index/io/filter_test.go
pkg/vm/engine/tae/index/io/zonemap_block.go
pkg/vm/engine/tae/index/io/zonemap_block_test.go
pkg/vm/engine/tae/index/io/zonemap_segment.go
pkg/vm/engine/tae/index/io/zonemap_segment_test.go

issue #
Not Available
Not Available
Not Available

(tae): add segment zone map index & format index codes

---

pkg/vm/engine/tae/catalog/block.go
pkg/vm/engine/tae/catalog/segment.go
pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/catalog/types.go
pkg/vm/engine/tae/db/catalog_test.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/iface/handle/block.go
pkg/vm/engine/tae/iface/handle/relation.go
pkg/vm/engine/tae/iface/handle/segment.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/txn/txnbase/handle.go
pkg/vm/engine/tae/txn/txnbase/store.go
pkg/vm/engine/tae/txn/txnimpl/block.go
pkg/vm/engine/tae/txn/txnimpl/relation.go
pkg/vm/engine/tae/txn/txnimpl/segment.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/table.go

issue #
Not Available
Not Available
Not Available

(tae): update for more txn operations

---

pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/iface/handle/segment.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/updates/delchain.go
pkg/vm/engine/tae/txn/txnbase/handle.go
pkg/vm/engine/tae/txn/txnbase/store.go
pkg/vm/engine/tae/txn/txnimpl/block.go
pkg/vm/engine/tae/txn/txnimpl/segment.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/table.go

issue #
Not Available
Not Available
Not Available

(tae): add more test

---

pkg/vm/engine/tae/container/compute/compute.go
pkg/vm/engine/tae/container/compute/compute_test.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/iface/handle/relation.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/node.go
pkg/vm/engine/tae/tables/updates/colupdate.go
pkg/vm/engine/tae/tables/updates/delete.go
pkg/vm/engine/tae/tasks/compactblk.go
pkg/vm/engine/tae/txn/txnbase/handle.go
pkg/vm/engine/tae/txn/txnimpl/ctx.go
pkg/vm/engine/tae/txn/txnimpl/relation.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/table.go

issue #
Not Available
Not Available
Not Available

prepare for transactional block compaction

---

pkg/vm/engine/tae/tables/block.go

issue #
Not Available
Not Available
Not Available

(tae): add some todo

---

pkg/vm/engine/tae/container/compute/mock.go
pkg/vm/engine/tae/dataio/mockio/block.go
pkg/vm/engine/tae/dataio/mockio/colblk.go
pkg/vm/engine/tae/dataio/mockio/segment.go
pkg/vm/engine/tae/dataio/mockio/segment_test.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/iface/file/block.go
pkg/vm/engine/tae/iface/file/segment.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/updates/dataview.go

issue #
Not Available
Not Available
Not Available

(tae): update for block and segment file

---

pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/tables/block.go

issue #
Not Available
Not Available
Not Available

(tae): update get vector copy for non appendable block

---

pkg/vm/engine/tae/index/access/acif/ifaces.go
pkg/vm/engine/tae/index/access/impl/ablock.go
pkg/vm/engine/tae/index/access/impl/block.go
pkg/vm/engine/tae/index/basic/filter.go
pkg/vm/engine/tae/index/basic/filter_test.go
pkg/vm/engine/tae/index/io/filter.go
pkg/vm/engine/tae/index/io/filter_test.go
pkg/vm/engine/tae/tables/block.go

TODO: deal with index holder upgrading, initializing index readers from meta, and integrate with compaction logic afterwards
issue #
Not Available
Not Available
Not Available

(tae): add non-appendable block index holder

---

pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/iface/handle/block.go
pkg/vm/engine/tae/iface/handle/segment.go
pkg/vm/engine/tae/tables/appender.go
pkg/vm/engine/tae/tasks/compactblk.go
pkg/vm/engine/tae/txn/txnbase/handle.go
pkg/vm/engine/tae/txn/txnimpl/antidepend.go
pkg/vm/engine/tae/txn/txnimpl/block.go
pkg/vm/engine/tae/txn/txnimpl/segment.go
pkg/vm/engine/tae/txn/txnimpl/table.go

issue #
Not Available
Not Available
Not Available

(tae): fix bugs and update for block compaction

---

pkg/vm/engine/tae/tables/block.go

issue #
Not Available
Not Available
Not Available

(tae): temp fix for ut

---

pkg/vm/engine/tae/common/utils.go
pkg/vm/engine/tae/container/vector/stdvec.go
pkg/vm/engine/tae/container/vector/strvec.go
pkg/vm/engine/tae/container/vector/types.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/txn/txnimpl/node.go
pkg/vm/engine/tae/txn/txnimpl/table.go

issue #
Not Available
Not Available
Not Available

Update prepareAppend and ApplyAppend

---

pkg/vm/engine/tae/checkpoint/driver.go
pkg/vm/engine/tae/checkpoint/types.go
pkg/vm/engine/tae/checkpoint/units.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/schedule_test.go
pkg/vm/engine/tae/db/task.go
pkg/vm/engine/tae/db/timer.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/iface/handle/block.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tasks/base.go
pkg/vm/engine/tae/txn/txnbase/handle.go
pkg/vm/engine/tae/txn/txnimpl/block.go

issue #
Not Available
Not Available
Not Available

update for checkpoint

---

pkg/vm/engine/tae/container/vector/stdvec.go
pkg/vm/engine/tae/container/vector/strvec.go
pkg/vm/engine/tae/dataio/mockio/block.go
pkg/vm/engine/tae/db/catalog_test.go
pkg/vm/engine/tae/db/db.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/schedule_test.go
pkg/vm/engine/tae/db/task.go
pkg/vm/engine/tae/samples/sample1/main.go
pkg/vm/engine/tae/samples/sample2/main.go
pkg/vm/engine/tae/samples/sample3/main.go
pkg/vm/engine/tae/samples/sample4/main.go
pkg/vm/engine/tae/tables/appender.go
pkg/vm/engine/tae/tables/node.go

issue #
Not Available
Not Available
Not Available

update unload related

---

pkg/vm/engine/tae/db/db.go
pkg/vm/engine/tae/db/open.go

issue #
Not Available
Not Available
Not Available

(tae): fix typo

---

pkg/vm/engine/tae/tables/txnentries/compactblk.go
pkg/vm/engine/tae/tables/txnentries/mergeblocks.go

issue #
Not Available
Not Available
Not Available

(tae): add mergeblocks

---

pkg/vm/engine/tae/dataio/mockio/block.go
pkg/vm/engine/tae/db/tables_test.go
pkg/vm/engine/tae/iface/file/block.go
pkg/vm/engine/tae/tables/jobs/mergeblocks.go

issue #
Not Available
Not Available
Not Available

update for merge blocks

---

pkg/vm/engine/tae/common/compare.go
pkg/vm/engine/tae/common/file.go
pkg/vm/engine/tae/common/utils.go
pkg/vm/engine/tae/container/compute/compute.go
pkg/vm/engine/tae/container/compute/compute_test.go
pkg/vm/engine/tae/dataio/mockio/block.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/iface/file/block.go
pkg/vm/engine/tae/index/access/acif/ifaces.go
pkg/vm/engine/tae/index/access/impl/ablock.go
pkg/vm/engine/tae/index/access/impl/block.go
pkg/vm/engine/tae/index/basic/filter_test.go
pkg/vm/engine/tae/index/common/meta.go
pkg/vm/engine/tae/index/common/mock.go
pkg/vm/engine/tae/index/io/filter.go
pkg/vm/engine/tae/index/io/filter_test.go
pkg/vm/engine/tae/index/io/zonemap_block.go
pkg/vm/engine/tae/index/io/zonemap_block_test.go
pkg/vm/engine/tae/index/io/zonemap_segment.go
pkg/vm/engine/tae/index/io/zonemap_segment_test.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/jobs/compactblk.go

issue #
Not Available
Not Available
Not Available

(tae): update non-appendable block index

---

pkg/vm/engine/tae/catalog/base.go
pkg/vm/engine/tae/catalog/segment.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/db/schedule.go
pkg/vm/engine/tae/db/schedule_test.go
pkg/vm/engine/tae/db/tables_test.go
pkg/vm/engine/tae/db/timer.go
pkg/vm/engine/tae/db/txn_test.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/jobs/flushablk.go
pkg/vm/engine/tae/tables/node.go
pkg/vm/engine/tae/tables/tables.go
pkg/vm/engine/tae/tasks/dispatcher.go
pkg/vm/engine/tae/tasks/schedule.go
pkg/vm/engine/tae/tasks/types.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/txn/txnimpl/txn_test.go
pkg/vm/engine/tae/worker/worker.go

issue #
Not Available
Not Available
Not Available

update for io scheduler and fix bugs

---

pkg/vm/engine/tae/catalog/schema.go
pkg/vm/engine/tae/checkpoint/driver.go
pkg/vm/engine/tae/checkpoint/policy.go
pkg/vm/engine/tae/checkpoint/units.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/db/schedule.go
pkg/vm/engine/tae/db/schedule_test.go
pkg/vm/engine/tae/db/tables_test.go
pkg/vm/engine/tae/db/txn_test.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/iface/handle/block.go
pkg/vm/engine/tae/moengine/block.go
pkg/vm/engine/tae/options/cfg.go
pkg/vm/engine/tae/options/options.go
pkg/vm/engine/tae/options/types.go
pkg/vm/engine/tae/samples/sample2/main.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/jobs/compactblk.go
pkg/vm/engine/tae/tables/jobs/flushblk.go
pkg/vm/engine/tae/tables/jobs/mergeblocks.go
pkg/vm/engine/tae/tables/node.go
pkg/vm/engine/tae/txn/txnbase/handle.go
pkg/vm/engine/tae/txn/txnimpl/block.go

issue #
Not Available
Not Available
Not Available

update checkpoint and some refactor

---

pkg/vm/engine/tae/container/compute/compute.go
pkg/vm/engine/tae/container/compute/compute_test.go
pkg/vm/engine/tae/tables/block.go

issue #
Not Available
Not Available
Not Available

(tae): optimize deletes check

---

pkg/vm/engine/tae/catalog/schema.go
pkg/vm/engine/tae/container/compute/compute.go
pkg/vm/engine/tae/container/compute/compute_test.go
pkg/vm/engine/tae/container/vector/wrapper.go
pkg/vm/engine/tae/dataio/mockio/block.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/iface/handle/block.go
pkg/vm/engine/tae/tables/appender.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/node.go
pkg/vm/engine/tae/tables/updates/append.go
pkg/vm/engine/tae/tables/updates/chain_test.go
pkg/vm/engine/tae/tables/updates/delchain.go
pkg/vm/engine/tae/tables/updates/mvcc.go
pkg/vm/engine/tae/tables/updates/mvcc_test.go
pkg/vm/engine/tae/tables/updates/updatechain.go
pkg/vm/engine/tae/tasks/base.go

issue #
Not Available
Not Available
Not Available

update for get by filter and some refactor

---

pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/iface/handle/relation.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/index/basic/zonemap.go
pkg/vm/engine/tae/txn/txnbase/handle.go
pkg/vm/engine/tae/txn/txnbase/store.go
pkg/vm/engine/tae/txn/txnbase/txn.go
pkg/vm/engine/tae/txn/txnimpl/relation.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/txn/txnimpl/txn_test.go

issue #
Not Available
Not Available
Not Available

update for txn and fix bugs

---

pkg/vm/engine/tae/db/db.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/txn/txnbase/node.go
pkg/vm/engine/tae/txn/txnbase/txnmgr.go
pkg/vm/engine/tae/txn/txnimpl/cmdmgr.go
pkg/vm/engine/tae/txn/txnimpl/node.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/txn/txnimpl/txn_test.go
pkg/vm/engine/tae/wal/driver.go
pkg/vm/engine/tae/wal/types.go

issue #
Not Available
Not Available
Not Available

update for wal and data block

---

pkg/vm/engine/tae/index/basic/zonemap.go

issue #
Not Available
Not Available
Not Available

(tae): small fix for zonemap unmarshal

---

pkg/vm/engine/tae/catalog/base.go
pkg/vm/engine/tae/catalog/block.go
pkg/vm/engine/tae/catalog/database.go
pkg/vm/engine/tae/catalog/segment.go
pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/tables/txnentries/compactblk.go
pkg/vm/engine/tae/tables/updates/append.go
pkg/vm/engine/tae/tables/updates/cmd.go
pkg/vm/engine/tae/tables/updates/colupdate.go
pkg/vm/engine/tae/tables/updates/delete.go
pkg/vm/engine/tae/txn/txnbase/errors.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/txn/txnimpl/txn_test.go

issue #
Not Available
Not Available
Not Available

optimize txnimpl

---

pkg/vm/engine/tae/catalog/base.go
pkg/vm/engine/tae/catalog/mock.go
pkg/vm/engine/tae/catalog/relhandle.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/tables/txnentries/compactblk.go
pkg/vm/engine/tae/tables/updates/append.go
pkg/vm/engine/tae/tables/updates/chain_test.go
pkg/vm/engine/tae/tables/updates/colupdate.go
pkg/vm/engine/tae/tables/updates/delete.go
pkg/vm/engine/tae/tables/updates/mvcc_test.go
pkg/vm/engine/tae/txn/txnimpl/cmdmgr.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/wal/types.go

issue #
Not Available
Not Available
Not Available

change apply commit

---

pkg/vm/engine/tae/logstore/entry/base.go
pkg/vm/engine/tae/logstore/entry/entry_test.go
pkg/vm/engine/tae/logstore/store/file_test.go
pkg/vm/engine/tae/logstore/store/replayer.go
pkg/vm/engine/tae/logstore/store/store_test.go
pkg/vm/engine/tae/logstore/store/syncbase.go
pkg/vm/engine/tae/logstore/store/vgroup.go
pkg/vm/engine/tae/logstore/store/vinfo.go
pkg/vm/engine/tae/wal/driver.go
pkg/vm/engine/tae/wal/types.go
pkg/vm/engine/tae/wal/wal_test.go

issue #
Not Available
Not Available
Not Available

(tae): checkpoint interface

---

pkg/vm/engine/tae/logstore/store/file.go
pkg/vm/engine/tae/logstore/store/store.go
pkg/vm/engine/tae/wal/wal_test.go

issue #
Not Available
Not Available
Not Available

(tae): fix logstore

---

pkg/vm/engine/tae/logstore/entry/base.go
pkg/vm/engine/tae/logstore/entry/types.go
pkg/vm/engine/tae/logstore/store/file_test.go
pkg/vm/engine/tae/logstore/store/store.go
pkg/vm/engine/tae/logstore/store/store_test.go
pkg/vm/engine/tae/logstore/store/syncbase.go
pkg/vm/engine/tae/logstore/store/vfile.go
pkg/vm/engine/tae/logstore/store/vgroup.go
pkg/vm/engine/tae/logstore/store/vinfo.go
pkg/vm/engine/tae/wal/wal_test.go

issue #
Not Available
Not Available
Not Available

tae: update logstore

---

pkg/vm/engine/tae/common/intervals.go
pkg/vm/engine/tae/logstore/store/store_test.go
pkg/vm/engine/tae/logstore/store/syncbase.go
pkg/vm/engine/tae/logstore/store/types.go
pkg/vm/engine/tae/tables/txnentries/compactblk.go
pkg/vm/engine/tae/wal/driver.go
pkg/vm/engine/tae/wal/types.go
pkg/vm/engine/tae/wal/wal_test.go

issue #
Not Available
Not Available
Not Available

(tae): add GetPenddingCnt, add GetCurrSeqNum

---

pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/tables/blocktasks.go
pkg/vm/engine/tae/tables/jobs/mergeblocks.go

issue #
Not Available
Not Available
Not Available

(tae): update for merge blocks

---

pkg/vm/engine/tae/catalog/base.go
pkg/vm/engine/tae/catalog/checkpoint.go
pkg/vm/engine/tae/catalog/filter.go
pkg/vm/engine/tae/db/catalog_test.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/moengine/engine.go
pkg/vm/engine/tae/samples/sample4/main.go
pkg/vm/engine/tae/txn/txnbase/store.go
pkg/vm/engine/tae/txn/txnbase/txn.go
pkg/vm/engine/tae/txn/txnimpl/block.go
pkg/vm/engine/tae/txn/txnimpl/database.go
pkg/vm/engine/tae/txn/txnimpl/relation.go
pkg/vm/engine/tae/txn/txnimpl/segment.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/txn.go

issue #
Not Available
Not Available
Not Available

add show databases and fix bugs

---

pkg/vm/engine/tae/tables/jobs/flushblk.go
pkg/vm/engine/tae/tables/jobs/helper.go
pkg/vm/engine/tae/tables/jobs/mergeblocks.go

issue #
Not Available
Not Available
Not Available

(tae): build block index during merge blocks

---

pkg/vm/engine/tae/catalog/base.go
pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/dataio/mockio/block.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/scannerop.go
pkg/vm/engine/tae/db/tables_test.go
pkg/vm/engine/tae/db/txn_test.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/iface/handle/relation.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/blocktasks.go
pkg/vm/engine/tae/tables/jobs/compactablk.go
pkg/vm/engine/tae/tables/jobs/mergeblocks.go
pkg/vm/engine/tae/tables/node.go
pkg/vm/engine/tae/tables/segment.go
pkg/vm/engine/tae/tables/txnentries/command_test.go
pkg/vm/engine/tae/tables/txnentries/compactblk.go
pkg/vm/engine/tae/tables/txnentries/compactblkcmd.go
pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
pkg/vm/engine/tae/tables/txnentries/mergeblockscmd.go
pkg/vm/engine/tae/tables/updates/append.go
pkg/vm/engine/tae/tables/updates/mvcc.go
pkg/vm/engine/tae/tasks/types.go
pkg/vm/engine/tae/txn/txnbase/handle.go
pkg/vm/engine/tae/txn/txnbase/store.go
pkg/vm/engine/tae/txn/txnimpl/relation.go
pkg/vm/engine/tae/txn/txnimpl/store.go
pkg/vm/engine/tae/txn/txnimpl/table.go

issue #
Not Available
Not Available
Not Available

update for async compaction tasks

---

pkg/vm/engine/tae/tables/txnentries/command_test.go
pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
pkg/vm/engine/tae/tables/txnentries/mergeblockscmd.go

issue #
Not Available
Not Available
Not Available

tae: update mergeBlocksCmd

---

pkg/vm/engine/tae/dataio/mockio/block.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/index/access/acif/ifaces.go
pkg/vm/engine/tae/index/access/impl/ablock.go
pkg/vm/engine/tae/index/access/impl/block.go
pkg/vm/engine/tae/index/io/filter.go
pkg/vm/engine/tae/index/io/zonemap_block.go
pkg/vm/engine/tae/tables/block.go

issue #
Not Available
Not Available
Not Available

(tae): add block index destructor

---

pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/catalog/checkpoint.go
pkg/vm/engine/tae/db/catalog_test.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/db/gc_test.go
pkg/vm/engine/tae/db/scannerop.go
pkg/vm/engine/tae/db/scheduler.go
pkg/vm/engine/tae/db/scheduler_test.go
pkg/vm/engine/tae/db/tables_test.go
pkg/vm/engine/tae/db/txn_test.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/iface/handle/block.go
pkg/vm/engine/tae/index/access/impl/ablock.go
pkg/vm/engine/tae/index/access/impl/block.go
pkg/vm/engine/tae/model/blkview.go
pkg/vm/engine/tae/model/blkview_test.go
pkg/vm/engine/tae/model/colview.go
pkg/vm/engine/tae/moengine/block.go
pkg/vm/engine/tae/samples/sample2/main.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/blocktasks.go
pkg/vm/engine/tae/tables/jobs/compactblk.go
pkg/vm/engine/tae/tables/jobs/mergeblocks.go
pkg/vm/engine/tae/tables/txnentries/compactblk.go
pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
pkg/vm/engine/tae/tasks/scheduler.go
pkg/vm/engine/tae/txn/txnbase/handle.go
pkg/vm/engine/tae/txn/txnimpl/block.go

issue #
Not Available
Not Available
Not Available

refactor and bug fix

---

pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/catalog/command.go
pkg/vm/engine/tae/logstore/store/history.go
pkg/vm/engine/tae/logstore/store/store.go
pkg/vm/engine/tae/logstore/store/syncbase.go
pkg/vm/engine/tae/txn/txnimpl/command_test.go

issue #
Not Available
Not Available
Not Available

tae: replay catalog 

---

pkg/vm/engine/tae/catalog/catalog.go

issue #
Not Available
Not Available
Not Available

tae: fix catalog replay

---

pkg/vm/engine/tae/db/replay.go
pkg/vm/engine/tae/txn/txnimpl/appendcmd.go
pkg/vm/engine/tae/txn/txnimpl/command_test.go
pkg/vm/engine/tae/txn/txnimpl/node.go
pkg/vm/engine/tae/txn/txnimpl/table.go

issue #
Not Available
Not Available
Not Available

add onReplayAppendCmd

---

pkg/vm/engine/tae/db/replay.go
pkg/vm/engine/tae/iface/data/block.go
pkg/vm/engine/tae/tables/appender.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/updates/append.go
pkg/vm/engine/tae/tables/updates/cmd.go
pkg/vm/engine/tae/tables/updates/colupdate.go
pkg/vm/engine/tae/tables/updates/delete.go

issue #
Not Available
Not Available
Not Available

add onReplayUpdateCmd

---

pkg/vm/engine/tae/tables/updates/chain_test.go
pkg/vm/engine/tae/tables/updates/cmd.go
pkg/vm/engine/tae/tables/updates/command_test.go

issue #
Not Available
Not Available
Not Available

fix updatas ut

---

pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/db/replay.go
pkg/vm/engine/tae/txn/txnbase/command.go
pkg/vm/engine/tae/txn/txnimpl/cmdmgr.go

issue #
Not Available
Not Available
Not Available

update replay logindex

---

pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/catalog/command.go
pkg/vm/engine/tae/catalog/replay.go
pkg/vm/engine/tae/db/db.go
pkg/vm/engine/tae/db/replay.go
pkg/vm/engine/tae/db/replay_test.go
pkg/vm/engine/tae/logstore/store/replayer.go
pkg/vm/engine/tae/logstore/store/store_test.go
pkg/vm/engine/tae/logstore/store/types.go
pkg/vm/engine/tae/txn/txnimpl/node.go

issue #
Not Available
Not Available
Not Available

update replay ut

---

pkg/vm/engine/tae/catalog/block.go
pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/logstore/store/replayer.go
pkg/vm/engine/tae/logstore/store/store.go
pkg/vm/engine/tae/logstore/store/vfile.go

issue #
Not Available
Not Available
Not Available

fix replay catalog id

---

pkg/vm/engine/tae/dataio/segmentio/log.go

issue #
Not Available
Not Available
Not Available

Fix bug of remove empty file

---

pkg/vm/engine/tae/dataio/mockio/block.go
pkg/vm/engine/tae/dataio/segmentio/block.go
pkg/vm/engine/tae/dataio/segmentio/segment.go
pkg/vm/engine/tae/dataio/segmentio/segment_test.go
pkg/vm/engine/tae/iface/file/block.go

issue #
Not Available
Not Available
Not Available

Add delete file stat

---

pkg/vm/engine/tae/dataio/segmentio/segment.go

issue #
Not Available
Not Available
Not Available

Fix the bug that the update file expires

---

pkg/vm/engine/tae/containers/utils.go
pkg/vm/engine/tae/db/txn_test.go
pkg/vm/engine/tae/tables/appender.go
pkg/vm/engine/tae/txn/txnimpl/relation.go

issue #
Not Available
Not Available
Not Available

(tae): fix some bug

---

pkg/vm/engine/tae/moengine/relation.go
pkg/vm/engine/tae/moengine/utils.go
test/result/dml/show/show.result

issue #
Not Available
Not Available
Not Available

Add MOToVectorTmp

---

pkg/vm/engine/tae/db/replay.go

issue #
Not Available
Not Available
Not Available

fix onReplayUpdate

---

pkg/vm/engine/tae/containers/factory.go
pkg/vm/engine/tae/moengine/relation.go
pkg/vm/engine/tae/moengine/utils.go

issue #
Not Available
Not Available
Not Available

Update moengine support type any

---

pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/mergesort/mergesort.go
pkg/vm/engine/tae/mergesort/mergesort_test.go
pkg/vm/engine/tae/tables/jobs/compactblk.go
pkg/vm/engine/tae/tables/txnentries/compactblk.go

issue #
Not Available
Not Available
Not Available

fix compact

---

pkg/vm/engine/tae/compute/compute.go
pkg/vm/engine/tae/compute/compute_test.go
pkg/vm/engine/tae/db/base_test.go
pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/mergesort/mergesort_test.go
pkg/vm/engine/tae/tables/jobs/compactblk.go
pkg/vm/engine/tae/tables/jobs/mergeblocks.go
pkg/vm/engine/tae/tables/txnentries/compactblk.go
pkg/vm/engine/tae/tables/txnentries/mergeblocks.go

issue #
Not Available
Not Available
Not Available

update compact block

---

pkg/vm/engine/tae/dataio/segmentio/block.go
pkg/vm/engine/tae/dataio/segmentio/colblk.go
pkg/vm/engine/tae/dataio/segmentio/data.go

issue #
Not Available
Not Available
Not Available

Fix data race

---

pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/tables/block.go
pkg/vm/engine/tae/tables/updates/chain_test.go
pkg/vm/engine/tae/tables/updates/colupdate.go
pkg/vm/engine/tae/tables/updates/delchain.go
pkg/vm/engine/tae/tables/updates/delete.go
pkg/vm/engine/tae/tables/updates/mvcc.go
pkg/vm/engine/tae/tables/updates/updatechain.go
pkg/vm/engine/tae/tables/updates/updateview.go

issue #
Not Available
Not Available
Not Available

replace DLNode

---

pkg/vm/engine/tae/catalog/base.go
pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/catalog/node_test.go
pkg/vm/engine/tae/catalog/updatenode.go

issue #
Not Available
Not Available
Not Available

use generic dlnode in catalog

---

pkg/vm/engine/tae/dataio/blockio/writer.go

issue #
Not Available
Not Available
Not Available

Update writer's WriteBlock

---

pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/tables/jobs/compactblk.go
pkg/vm/engine/tae/tables/txnentries/compactblk.go

add mapping vector

---

pkg/vm/engine/tae/db/db_test.go
pkg/vm/engine/tae/tables/txnentries/mergeblocks.go

add transfer page in merge

---

test/distributed/resources/into_outfile/.gitignore
test/distributed/resources/into_outfile_2/.gitignore

Readd .gitignore

---

pkg/vm/engine/tae/db/merge/policyBasic.go

fix useless

---

pkg/vm/engine/tae/catalog/catalog.go
pkg/vm/engine/tae/catalog/catalogreplay.go
pkg/vm/engine/tae/catalog/object.go
pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/catalog/tablemvccnode.go
pkg/vm/engine/tae/catalog/types.go
pkg/vm/engine/tae/db/checkpoint/entry.go
pkg/vm/engine/tae/db/checkpoint/replay.go
pkg/vm/engine/tae/db/checkpoint/runner.go
pkg/vm/engine/tae/db/gc/table.go
pkg/vm/engine/tae/db/test/db_test.go
pkg/vm/engine/tae/db/test/storage_usage_test.go
pkg/vm/engine/tae/db/testutil/engine.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/logtail/backup.go
pkg/vm/engine/tae/logtail/handle.go
pkg/vm/engine/tae/logtail/operator.go
pkg/vm/engine/tae/logtail/snapshot.go
pkg/vm/engine/tae/logtail/storage_usage.go
pkg/vm/engine/tae/logtail/tools.go
pkg/vm/engine/tae/logtail/txn_handle.go
pkg/vm/engine/tae/logtail/types.go
pkg/vm/engine/tae/logtail/utils.go
pkg/vm/engine/tae/txn/txnbase/store.go
pkg/vm/engine/tae/txn/txnimpl/store.go

update push and pull

---

pkg/objectio/writer_test.go

Fix UT (#136)

---

pkg/frontend/show_account.go

fix compile

---

pkg/vm/engine/tae/catalog/object.go
pkg/vm/engine/tae/db/test/db_test.go
pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
pkg/vm/engine/tae/tables/txnentries/mergeobjects.go

small updates

---

pkg/vm/engine/tae/catalog/deletelist.go
pkg/vm/engine/tae/catalog/table.go
pkg/vm/engine/tae/db/test/db_test.go
pkg/vm/engine/tae/rpc/handle_debug.go
pkg/vm/engine/tae/tables/jobs/flushTableTail.go
pkg/vm/engine/tae/tables/jobs/mergeobjects.go
pkg/vm/engine/tae/tables/tombstone.go
pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
pkg/vm/engine/tae/tables/txnentries/mergeobjects.go

Tombstone merge

---

pkg/vm/engine/disttae/merge.go
pkg/vm/engine/tae/db/testutil/funcs.go
pkg/vm/engine/tae/index/indexwrapper/immutindex.go
pkg/vm/engine/tae/index/types.go
pkg/vm/engine/tae/mergesort/task.go
pkg/vm/engine/tae/rpc/rpc_test.go
pkg/vm/engine/tae/tables/base.go
pkg/vm/engine/tae/tables/jobs/flushTableTail.go
pkg/vm/engine/tae/tables/jobs/flushobj.go
pkg/vm/engine/tae/tables/jobs/mergeobjects.go
pkg/vm/engine/tae/tables/pnode.go
pkg/vm/engine/tae/txn/txnimpl/table.go

use bloomfilter

---

pkg/vm/engine/tae/catalog/schema.go
pkg/vm/engine/tae/db/test/db_test.go
pkg/vm/engine/tae/tables/jobs/flushTableTail.go
pkg/vm/engine/tae/tables/jobs/mergeobjects.go
pkg/vm/engine/tae/tables/mnode.go
pkg/vm/engine/tae/tables/pnode.go
pkg/vm/engine/tae/tables/updates/mvcc.go
pkg/vm/engine/tae/tables/utils.go
pkg/vm/engine/tae/txn/txnimpl/object.go

flush commit ts for tombstone in merge & flush

---

pkg/vm/engine/tae/iface/data/object.go
pkg/vm/engine/tae/tables/aobj.go
pkg/vm/engine/tae/tables/obj.go

fix dead lock

---

pkg/vm/engine/tae/model/tree.go

fix replay WAL

---

pkg/vm/engine/test/disttae_engine_test.go
pkg/vm/engine/test/partition_state_test.go

skip pstate UTs

---

pkg/vm/engine/disttae/db.go
pkg/vm/engine/disttae/logtailreplay/partition.go
pkg/vm/engine/tae/db/checkpoint/info.go
pkg/vm/engine/tae/db/checkpoint/snapshot.go
pkg/vm/engine/tae/db/gc/v1/checkpoint.go
pkg/vm/engine/tae/db/gc/v2/checkpoint.go
pkg/vm/engine/tae/db/gc/v2/merge.go

Gcv2 1.3 merge checkpoint

---

pkg/objectio/object_stats.go
pkg/sql/colexec/s3util.go
pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
pkg/util/metric/v2/metrics.go
pkg/util/metric/v2/txn.go
pkg/vm/engine/disttae/datasource.go
pkg/vm/engine/disttae/datasource_test.go
pkg/vm/engine/disttae/logtailreplay/blocks_iter_inprogress.go
pkg/vm/engine/disttae/tombstones.go
pkg/vm/engine/disttae/txn.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/disttae/types.go
pkg/vm/engine/tae/blockio/read.go
pkg/vm/engine/tae/blockio/writer.go
pkg/vm/engine/tae/catalog/catalogreplay.go
pkg/vm/engine/tae/catalog/metamvccnode.go
pkg/vm/engine/tae/catalog/object.go
pkg/vm/engine/tae/db/merge/executor.go
pkg/vm/engine/tae/db/merge/mod.go
pkg/vm/engine/tae/db/merge/policyBasic.go
pkg/vm/engine/tae/db/merge/utils.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/db/scannerop.go
pkg/vm/engine/tae/db/test/db_test.go
pkg/vm/engine/tae/mergesort/merger.go
pkg/vm/engine/tae/tables/jobs/flushTableTail.go
pkg/vm/engine/tae/tables/jobs/flushobj.go
pkg/vm/engine/tae/tables/pnode.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/types.go

Reverts XuPeng-SH/matrixone#179

Revert "Partition state handle tombstone logtail"

---

pkg/vm/engine/tae/logtail/tools.go
pkg/vm/engine/tae/logtail/txn_handle.go

update logtail, add phyaddrColumn in delete batch

---

pkg/vm/engine/disttae/tombstones.go

add coarse check tombstone

---

pkg/vm/engine/disttae/db.go
pkg/vm/engine/tae/db/open.go
pkg/vm/engine/tae/tables/obj.go

Storage tombstone dev debug 2

---

pkg/vm/engine/disttae/datasource.go

fix tombstone zm compare

---

pkg/sql/colexec/deletion/types.go

sort cn tombstones by block id

---

pkg/vm/engine/tae/db/gc/v2/checkpoint.go
pkg/vm/engine/tae/db/gc/v2/table.go

Gcv2 1.3 fix TestSnapshotGC

---

pkg/vm/engine/disttae/datasource_test.go

add some ut

---

pkg/vm/engine/test/disttae_engine_test.go

* not finish, gc deletes
* need apply pstate tombstone after gc only inmem tombstone
* cannot gc the inmem tombstone when gc inmem data## What type of PR is this?
issue #

fix disttae ut

---

pkg/vm/engine/disttae/logtailreplay/blocks_iter_inprogress.go
pkg/vm/engine/test/partition_state_test.go

fix partition state ut

---

pkg/vm/engine/disttae/datasource.go

disable prefetch tombstone object

---

pkg/vm/engine/disttae/datasource.go
pkg/vm/engine/tae/blockio/read.go
pkg/vm/engine/tae/logtail/snapshot.go
pkg/vm/engine/types.go

Batch apply tombstone object

---

pkg/vm/engine/disttae/datasource.go
pkg/vm/engine/tae/blockio/read.go
pkg/vm/engine/tae/index/hybrid_filter.go
pkg/vm/engine/tae/index/zm.go

(tombstone-dev): optimize apply tombstone objects

---

pkg/vm/engine/disttae/datasource.go
pkg/vm/engine/disttae/util.go

(tombstone-dev): use union one

---

pkg/vm/engine/tae/blockio/funcs.go
pkg/vm/engine/tae/blockio/read.go
pkg/vm/engine/tae/logtail/backup.go
pkg/vm/engine/tae/logtail/utils.go

Gc1.3 refactor backup

---

pkg/vm/engine/disttae/util_test.go

fix Test_ConstructBasePKFilter

---

pkg/vm/engine/tae/txn/txnimpl/table.go

(tombstone-dev): fix transfer

---

pkg/objectio/object_stats.go
pkg/vm/engine/tae/catalog/object.go
pkg/vm/engine/tae/tables/jobs/flushTableTail.go
pkg/vm/engine/tae/tables/jobs/mergeobjects.go
pkg/vm/engine/tae/txn/txnimpl/table_space.go

update object stats

---

pkg/vm/engine/disttae/logtailreplay/partition_state_inprogress.go

remove prefetch meta

---

pkg/vm/engine/tae/db/test/db_test.go
pkg/vm/engine/tae/tables/table_scan.go
pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
pkg/vm/engine/tae/tables/txnentries/mergeobjects.go

fix TombstoneRangeScanByObject

---

pkg/vm/engine/tae/rpc/rpc_test.go

fix ut failed by SetCNCreated check

---

pkg/vm/engine/tae/db/test/db_test.go
pkg/vm/engine/tae/iface/txnif/consts.go
pkg/vm/engine/tae/iface/txnif/types.go
pkg/vm/engine/tae/rpc/handle.go
pkg/vm/engine/tae/txn/txnbase/txn.go
pkg/vm/engine/tae/txn/txnimpl/base_table.go
pkg/vm/engine/tae/txn/txnimpl/table.go
pkg/vm/engine/tae/txn/txnimpl/table_space.go

update dedup policy

---

pkg/vm/engine/tae/tables/table_scan.go

fix data lost

---

pkg/vm/engine/disttae/datasource_test.go
pkg/vm/engine/disttae/txn_test.go

Disttae ut

---

pkg/vm/engine/disttae/txn_test.go

fix Test_GetUncommittedS3Tombstone

---

pkg/container/vector/vector.go
pkg/vm/engine/disttae/pk_filter_mem_test.go
pkg/vm/engine/engine_util/filter_test.go
pkg/vm/engine/engine_util/pk_filter.go

adding ut for pk filter

---

pkg/vm/engine/tae/blockio/utils.go
pkg/vm/engine/tae/blockio/utils_test.go

coarse filter tombstone object

---

pkg/sql/compile/compile.go

add lock meta error log

---

pkg/vm/engine/tae/db/checkpoint/testutils.go
pkg/vm/engine/tae/db/test/catalog_test.go
pkg/vm/engine/tae/db/test/db_test.go
pkg/vm/engine/tae/db/test/replay_test.go
pkg/vm/engine/tae/db/testutil/engine.go

remove incremental ckp

---

pkg/datasync/consumer_test.go
pkg/datasync/entry.go
pkg/datasync/entry_test.go
pkg/datasync/producer_test.go
pkg/vm/engine/tae/logstore/driver/logservicedriver/codec.go
pkg/vm/engine/tae/logstore/driver/logservicedriver/replayer.go
pkg/vm/engine/tae/logstore/driver/logservicedriver/v1.go

issue #
some fix of compatibility of log entry

some fix of compatibility of log entry
